GET  http://localhost:3000/getlists
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOnsiX2lkIjoiNjdiM2UzNjEzY2UxOTQ2NmU1MTI2NmRkIiwiZmlyc3ROYW1lIjoiNSIsImxhc3ROYW1lIjoiNSIsImVtYWlsIjoiNkBnbWFpbC5jb20iLCJwYXNzV29yZCI6IiQyYiQxMCRmU0lHNFVrcUZFMmpOdEt6WENNaEF1ck45RU43eGFiUnpXU0R2aGI5bW5URzdhLnB0NWllVyIsIl9fdiI6MH0sImlhdCI6MTczOTg5NDQ5MSwiZXhwIjoxNzM5ODk4MDkxfQ.xnlltSxVK-p1SSazCLazAJP79Xpb6CShSE1n3G1F_1o